from src.analysis.contrast import collect, frame_contrast, match_predictions
from src.analysis.overlay import draw_localization_grid, pick_examples
from src.analysis.report import (
    box_errors,
    contrast_control_summary,
    localization_decomposition,
    localization_summary,
    read_boxes_csv,
    plot_decomposition,
    plot_localization,
    plot_overview,
    plot_run_comparison,
    recall_by_contrast,
    recall_vs_iou_threshold,
    spread_by_contrast,
    summarize,
    write_csv,
)

__all__ = [
    "collect",
    "frame_contrast",
    "match_predictions",
    "summarize",
    "box_errors",
    "localization_decomposition",
    "localization_summary",
    "contrast_control_summary",
    "recall_by_contrast",
    "recall_vs_iou_threshold",
    "spread_by_contrast",
    "plot_overview",
    "plot_localization",
    "plot_decomposition",
    "plot_run_comparison",
    "draw_localization_grid",
    "pick_examples",
    "read_boxes_csv",
    "write_csv",
]
